name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  Build Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (without push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest

  Build and Run Tests:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run tests in Docker
        run: |
          docker build -t react-test .
          docker run --rm react-test npm test -- --ci --watchAll=false
